version: '3'
services:
  comments:
    #image: comments-docker-image build image to use in production
    build: './comments'
    ports:
      - "3000:3000"

  members:
    #image: members-docker-image build image to use in production
    build: './members'
    ports:
      - "3001:3000"